PREV_CALLBACK_ID = 1
NEXT_CALLBACK_ID = 2
CATEGORY_CALLBACK_ID = 3
LIKE_CALLBACK_ID = 4
ORDER_CALLBACK_ID = 5
INCR_CALLBACK_ID = 6
DECR_CALLBACK_ID = 7
AMOUNT_CALLBACK_ID = 8
SEEN_CALLBACK_ID = 9
ADD_CART_CALLBACK_ID = 10
CLEAR_CART_CALLBACK_ID = 11
CREATE_ORDER_CALLBACK_ID= 12
ADD_ORDER_COUNTRY_CALLBACK_ID = 13
ADD_ORDER_DELIVERY_CALLBACK_ID = 14
ADD_ORDER_PAYMENT_CALLBACK_ID = 15
EDIT_ORDER_CALLBACK_ID = 16
SUBMIT_ORDER_CALLBACK_ID = 17
CANCELLED_ORDER_CALLBACK_ID = 18

CALLBACK_MAP = {
    'next': NEXT_CALLBACK_ID,
    'prev': PREV_CALLBACK_ID,
    'category': CATEGORY_CALLBACK_ID,
    'like': LIKE_CALLBACK_ID,
    'order': ORDER_CALLBACK_ID,
    'incr': INCR_CALLBACK_ID,
    'decr': DECR_CALLBACK_ID,
    'amount': AMOUNT_CALLBACK_ID,
    'seen': SEEN_CALLBACK_ID,
    'add_cart': ADD_CART_CALLBACK_ID,
    'clear_cart': CLEAR_CART_CALLBACK_ID,
    'create_order': CREATE_ORDER_CALLBACK_ID,
    'choose_country': ADD_ORDER_COUNTRY_CALLBACK_ID,
    'choose_delivery': ADD_ORDER_DELIVERY_CALLBACK_ID,
    'choose_payment': ADD_ORDER_PAYMENT_CALLBACK_ID,
    'edit_order': EDIT_ORDER_CALLBACK_ID,
    'submit_order': SUBMIT_ORDER_CALLBACK_ID,
    'cancelled_order': CANCELLED_ORDER_CALLBACK_ID,
}
